// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mdfs/protos/datanode.proto
#ifndef GRPC_mdfs_2fprotos_2fdatanode_2eproto__INCLUDED
#define GRPC_mdfs_2fprotos_2fdatanode_2eproto__INCLUDED

#include "mdfs/protos/datanode.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace mdfs {
namespace message {

class DataNodeService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // between datanode
    // used for data communicate bewteen datanodes, e.g. duplication or checksum
    virtual ::grpc::Status Communicate(::grpc::ClientContext* context, const ::mdfs::message::DataNodeCommMessage& request, ::mdfs::message::DataNodeCommMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::DataNodeCommMessage>> AsyncCommunicate(::grpc::ClientContext* context, const ::mdfs::message::DataNodeCommMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::DataNodeCommMessage>>(AsyncCommunicateRaw(context, request, cq));
    }
    // from client to datanode
    // transfer a block between client and datanode
    virtual ::grpc::Status Transfer(::grpc::ClientContext* context, const ::mdfs::message::TransferMessage& request, ::mdfs::message::TransferReturnMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::TransferReturnMessage>> AsyncTransfer(::grpc::ClientContext* context, const ::mdfs::message::TransferMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::TransferReturnMessage>>(AsyncTransferRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::DataNodeCommMessage>* AsyncCommunicateRaw(::grpc::ClientContext* context, const ::mdfs::message::DataNodeCommMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::TransferReturnMessage>* AsyncTransferRaw(::grpc::ClientContext* context, const ::mdfs::message::TransferMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Communicate(::grpc::ClientContext* context, const ::mdfs::message::DataNodeCommMessage& request, ::mdfs::message::DataNodeCommMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::DataNodeCommMessage>> AsyncCommunicate(::grpc::ClientContext* context, const ::mdfs::message::DataNodeCommMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::DataNodeCommMessage>>(AsyncCommunicateRaw(context, request, cq));
    }
    ::grpc::Status Transfer(::grpc::ClientContext* context, const ::mdfs::message::TransferMessage& request, ::mdfs::message::TransferReturnMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::TransferReturnMessage>> AsyncTransfer(::grpc::ClientContext* context, const ::mdfs::message::TransferMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::TransferReturnMessage>>(AsyncTransferRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::mdfs::message::DataNodeCommMessage>* AsyncCommunicateRaw(::grpc::ClientContext* context, const ::mdfs::message::DataNodeCommMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mdfs::message::TransferReturnMessage>* AsyncTransferRaw(::grpc::ClientContext* context, const ::mdfs::message::TransferMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_Communicate_;
    const ::grpc::RpcMethod rpcmethod_Transfer_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // between datanode
    // used for data communicate bewteen datanodes, e.g. duplication or checksum
    virtual ::grpc::Status Communicate(::grpc::ServerContext* context, const ::mdfs::message::DataNodeCommMessage* request, ::mdfs::message::DataNodeCommMessage* response);
    // from client to datanode
    // transfer a block between client and datanode
    virtual ::grpc::Status Transfer(::grpc::ServerContext* context, const ::mdfs::message::TransferMessage* request, ::mdfs::message::TransferReturnMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Communicate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* context, const ::mdfs::message::DataNodeCommMessage* request, ::mdfs::message::DataNodeCommMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommunicate(::grpc::ServerContext* context, ::mdfs::message::DataNodeCommMessage* request, ::grpc::ServerAsyncResponseWriter< ::mdfs::message::DataNodeCommMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Transfer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Transfer() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Transfer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transfer(::grpc::ServerContext* context, const ::mdfs::message::TransferMessage* request, ::mdfs::message::TransferReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransfer(::grpc::ServerContext* context, ::mdfs::message::TransferMessage* request, ::grpc::ServerAsyncResponseWriter< ::mdfs::message::TransferReturnMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Communicate<WithAsyncMethod_Transfer<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Communicate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* context, const ::mdfs::message::DataNodeCommMessage* request, ::mdfs::message::DataNodeCommMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Transfer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Transfer() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Transfer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transfer(::grpc::ServerContext* context, const ::mdfs::message::TransferMessage* request, ::mdfs::message::TransferReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Communicate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::mdfs::message::DataNodeCommMessage, ::mdfs::message::DataNodeCommMessage>(std::bind(&WithStreamedUnaryMethod_Communicate<BaseClass>::StreamedCommunicate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* context, const ::mdfs::message::DataNodeCommMessage* request, ::mdfs::message::DataNodeCommMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCommunicate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mdfs::message::DataNodeCommMessage,::mdfs::message::DataNodeCommMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Transfer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Transfer() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::mdfs::message::TransferMessage, ::mdfs::message::TransferReturnMessage>(std::bind(&WithStreamedUnaryMethod_Transfer<BaseClass>::StreamedTransfer, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Transfer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Transfer(::grpc::ServerContext* context, const ::mdfs::message::TransferMessage* request, ::mdfs::message::TransferReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTransfer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mdfs::message::TransferMessage,::mdfs::message::TransferReturnMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Communicate<WithStreamedUnaryMethod_Transfer<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Communicate<WithStreamedUnaryMethod_Transfer<Service > > StreamedService;
};

}  // namespace message
}  // namespace mdfs


#endif  // GRPC_mdfs_2fprotos_2fdatanode_2eproto__INCLUDED
