// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mdfs/protos/namenode.proto
#ifndef GRPC_mdfs_2fprotos_2fnamenode_2eproto__INCLUDED
#define GRPC_mdfs_2fprotos_2fnamenode_2eproto__INCLUDED

#include "mdfs/protos/namenode.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace mdfs {
namespace message {

class NameNodeService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // from client to namenode
    // file system command
    virtual ::grpc::Status ClientCommand(::grpc::ClientContext* context, const ::mdfs::message::ClientCommandMessage& request, ::mdfs::message::ClientCommandReturnMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::ClientCommandReturnMessage>> AsyncClientCommand(::grpc::ClientContext* context, const ::mdfs::message::ClientCommandMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::ClientCommandReturnMessage>>(AsyncClientCommandRaw(context, request, cq));
    }
    // from datanode to namenode
    // tell namenode it still alive
    virtual ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::mdfs::message::HeartbeatMessage& request, ::mdfs::message::HeartbeatReturnMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::HeartbeatReturnMessage>> AsyncHeartbeat(::grpc::ClientContext* context, const ::mdfs::message::HeartbeatMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::HeartbeatReturnMessage>>(AsyncHeartbeatRaw(context, request, cq));
    }
    // from datanode to namenode
    // report a block status after read failure or write
    virtual ::grpc::Status ReportBlock(::grpc::ClientContext* context, const ::mdfs::message::ReportBlockMessage& request, ::mdfs::message::ReportBlockReturnMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::ReportBlockReturnMessage>> AsyncReportBlock(::grpc::ClientContext* context, const ::mdfs::message::ReportBlockMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::ReportBlockReturnMessage>>(AsyncReportBlockRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::ClientCommandReturnMessage>* AsyncClientCommandRaw(::grpc::ClientContext* context, const ::mdfs::message::ClientCommandMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::HeartbeatReturnMessage>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::mdfs::message::HeartbeatMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mdfs::message::ReportBlockReturnMessage>* AsyncReportBlockRaw(::grpc::ClientContext* context, const ::mdfs::message::ReportBlockMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ClientCommand(::grpc::ClientContext* context, const ::mdfs::message::ClientCommandMessage& request, ::mdfs::message::ClientCommandReturnMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::ClientCommandReturnMessage>> AsyncClientCommand(::grpc::ClientContext* context, const ::mdfs::message::ClientCommandMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::ClientCommandReturnMessage>>(AsyncClientCommandRaw(context, request, cq));
    }
    ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::mdfs::message::HeartbeatMessage& request, ::mdfs::message::HeartbeatReturnMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::HeartbeatReturnMessage>> AsyncHeartbeat(::grpc::ClientContext* context, const ::mdfs::message::HeartbeatMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::HeartbeatReturnMessage>>(AsyncHeartbeatRaw(context, request, cq));
    }
    ::grpc::Status ReportBlock(::grpc::ClientContext* context, const ::mdfs::message::ReportBlockMessage& request, ::mdfs::message::ReportBlockReturnMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::ReportBlockReturnMessage>> AsyncReportBlock(::grpc::ClientContext* context, const ::mdfs::message::ReportBlockMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mdfs::message::ReportBlockReturnMessage>>(AsyncReportBlockRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::mdfs::message::ClientCommandReturnMessage>* AsyncClientCommandRaw(::grpc::ClientContext* context, const ::mdfs::message::ClientCommandMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mdfs::message::HeartbeatReturnMessage>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::mdfs::message::HeartbeatMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mdfs::message::ReportBlockReturnMessage>* AsyncReportBlockRaw(::grpc::ClientContext* context, const ::mdfs::message::ReportBlockMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_ClientCommand_;
    const ::grpc::RpcMethod rpcmethod_Heartbeat_;
    const ::grpc::RpcMethod rpcmethod_ReportBlock_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // from client to namenode
    // file system command
    virtual ::grpc::Status ClientCommand(::grpc::ServerContext* context, const ::mdfs::message::ClientCommandMessage* request, ::mdfs::message::ClientCommandReturnMessage* response);
    // from datanode to namenode
    // tell namenode it still alive
    virtual ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::mdfs::message::HeartbeatMessage* request, ::mdfs::message::HeartbeatReturnMessage* response);
    // from datanode to namenode
    // report a block status after read failure or write
    virtual ::grpc::Status ReportBlock(::grpc::ServerContext* context, const ::mdfs::message::ReportBlockMessage* request, ::mdfs::message::ReportBlockReturnMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ClientCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ClientCommand() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ClientCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientCommand(::grpc::ServerContext* context, const ::mdfs::message::ClientCommandMessage* request, ::mdfs::message::ClientCommandReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClientCommand(::grpc::ServerContext* context, ::mdfs::message::ClientCommandMessage* request, ::grpc::ServerAsyncResponseWriter< ::mdfs::message::ClientCommandReturnMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Heartbeat() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::mdfs::message::HeartbeatMessage* request, ::mdfs::message::HeartbeatReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::mdfs::message::HeartbeatMessage* request, ::grpc::ServerAsyncResponseWriter< ::mdfs::message::HeartbeatReturnMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ReportBlock() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ReportBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportBlock(::grpc::ServerContext* context, const ::mdfs::message::ReportBlockMessage* request, ::mdfs::message::ReportBlockReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportBlock(::grpc::ServerContext* context, ::mdfs::message::ReportBlockMessage* request, ::grpc::ServerAsyncResponseWriter< ::mdfs::message::ReportBlockReturnMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ClientCommand<WithAsyncMethod_Heartbeat<WithAsyncMethod_ReportBlock<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_ClientCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ClientCommand() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ClientCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientCommand(::grpc::ServerContext* context, const ::mdfs::message::ClientCommandMessage* request, ::mdfs::message::ClientCommandReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Heartbeat() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::mdfs::message::HeartbeatMessage* request, ::mdfs::message::HeartbeatReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ReportBlock() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ReportBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportBlock(::grpc::ServerContext* context, const ::mdfs::message::ReportBlockMessage* request, ::mdfs::message::ReportBlockReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ClientCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ClientCommand() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::mdfs::message::ClientCommandMessage, ::mdfs::message::ClientCommandReturnMessage>(std::bind(&WithStreamedUnaryMethod_ClientCommand<BaseClass>::StreamedClientCommand, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ClientCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ClientCommand(::grpc::ServerContext* context, const ::mdfs::message::ClientCommandMessage* request, ::mdfs::message::ClientCommandReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedClientCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mdfs::message::ClientCommandMessage,::mdfs::message::ClientCommandReturnMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Heartbeat() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::mdfs::message::HeartbeatMessage, ::mdfs::message::HeartbeatReturnMessage>(std::bind(&WithStreamedUnaryMethod_Heartbeat<BaseClass>::StreamedHeartbeat, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::mdfs::message::HeartbeatMessage* request, ::mdfs::message::HeartbeatReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mdfs::message::HeartbeatMessage,::mdfs::message::HeartbeatReturnMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ReportBlock() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::StreamedUnaryHandler< ::mdfs::message::ReportBlockMessage, ::mdfs::message::ReportBlockReturnMessage>(std::bind(&WithStreamedUnaryMethod_ReportBlock<BaseClass>::StreamedReportBlock, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ReportBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportBlock(::grpc::ServerContext* context, const ::mdfs::message::ReportBlockMessage* request, ::mdfs::message::ReportBlockReturnMessage* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportBlock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mdfs::message::ReportBlockMessage,::mdfs::message::ReportBlockReturnMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ClientCommand<WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_ReportBlock<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ClientCommand<WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_ReportBlock<Service > > > StreamedService;
};

}  // namespace message
}  // namespace mdfs


#endif  // GRPC_mdfs_2fprotos_2fnamenode_2eproto__INCLUDED
